### PR TITLE
[DDO-2640] Have datarepo charts support BEE offline state

### PR DESCRIPTION
**Pull request by jack-r-warren**
We're adding an on/off switch for BEEs that works just by downscaling all the replicas to 0 -- https://github.com/broadinstitute/terra-helmfile/pull/3776

This if statement says "if .Values.global.replicasOffline exists and is true, use 0 for replicas, otherwise do whatever was there before." (Thelma conditionally pulls in the files that set that flag to true, and Sherlock enforces that this can only happen for BEEs.)

### CODE REVIEW

**Review by okotsopoulos — APPROVED** [review]

**Review by nmalfroy — CHANGES_REQUESTED** [review]
Cool, you also will need to update the chart versions for these

**Comment by jack-r-warren** [comment]
> Cool, you also will need to update the chart versions for these

@nmalfroy good call, yeah I suppose I'll need to update the umbrella chart in a subsequent PR too

**Comment by nmalfroy** [comment]
Oh, it'll update itself

**Comment by jack-r-warren** [comment]
> Oh, it'll update itself

Gotcha -- anything else to include here?

**Review by nmalfroy — APPROVED** [review]
I think this looks good!

**Pull request merged**
